name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Code (Clone Repository)
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java Environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Caching
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Ensure server has security rights to run gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Runs Lint, Unit Tests, and compiles the APK together
      - name: Build and Test Multi Module App
        run: ./gradlew lintDebug testDebugUnitTest assembleDebug --parallel --build-cache